apiVersion: apps/v1
kind: Deployment
metadata:
  name: tekton-pipelines-webhook
  labels:
    {{- with .Values.webhook.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- with .Values.webhook.pod.labels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      affinity:
        {{- with .Values.webhook.affinity }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: webhook
          envFrom:
            - secretRef:
                name: "{{ .Values.webhook.envFromSecret }}"
                optional: true
      nodeSelector:
        {{- with .Values.webhook.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      tolerations:
        {{- with .Values.webhook.tolerations }}
        {{- toYaml . | nindent 6 }}
        {{- end }}
